<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "its_pdfgen"
 *
 * Auto generated by Extension Builder 2013-11-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ITS PDF Generator',
	'description' => 'PDF Generator based on phantomjs workes also for password Protected Pages',
	'category' => 'plugin',
	'author' => 'Christoph Hofmann',
	'author_email' => 'typo3<add>its-hofmann.de',
	'author_company' => 'ITS Hofmann',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>